### ISSUE TITLE
Wi-Fi 模块（ESP8266）

### ISSUE THREAD

**Issue by leon80900** [HurleyChen/chl.github#19]
***2018年3月12日 更新***

- [ESP8266 + Airkiss从零开始实现微信配网](http://www.shaoguoji.cn/2017/01/16/ESP8266-wechat-onekey-config-1/)

***2017年10月23日 更新***

- [基于uCOS-II系统使用STM32和Esp8266对接Yeelink物联网平台的Demo](http://blog.csdn.net/Chuancey_CC/article/details/54799134)

***2017年10月16日 更新***

- [ESP8266 station模式下建立client、server TCP连接](http://www.cnblogs.com/CYP01/p/6336943.html)
- [ESP8266--学习笔记（四）TCP通信--TCP-Client](http://blog.csdn.net/qq_28877125/article/details/62898895)
--------
### 安信可官方教程
[ESP8266 常见问题](http://wiki.ai-thinker.com/esp8266/faq)
### CodingIndex的学习笔记

1. [基于STM32的ESP8266使用教程（一）](http://blog.csdn.net/qq_21229657/article/details/51697525)
2.  [ 基于STM32的ESP8266使用教程（二）](http://blog.csdn.net/qq_21229657/article/details/74011929)
3.  [ 基于STM32的ESP8266使用教程（三）](http://blog.csdn.net/qq_21229657/article/details/74104973)
4.  [基于STM32的ESP8266使用教程（四）（短篇）](http://blog.csdn.net/qq_21229657/article/details/74273226)

### [贝壳物联](https://github.com/bigiot)
- [ ] [远程控制通讯——基于STM32 + ESP8266控制LED灯并返回结果](https://www.bigiot.net/help/35.html)

----

-  [stm32和esp8266程序资料分析](http://blog.csdn.net/xs15073722800/article/details/50215419)  [百度云（密码：s0au）](http://pan.baidu.com/s/1gd77Fe7)

-  [**STM32学习笔记：ESP8266模块（1）**](http://blog.csdn.net/qq_33559992/article/details/52042412?utm_source=itdadao&utm_medium=referral)
- [**ESP8266玩转AT指令**](http://blog.csdn.net/jianghuiquan/article/details/60963008)
-  [STM32+ESP8266实现UDP通信](http://blog.mcujc.com/post/506.html)

-  [stm32f1精英版ESP8266 模块使用注意事项](http://blog.csdn.net/feixiang222teng/article/details/51649269)

-  [android客服端+eps8266+单片机+路由器之远程控制系统](http://www.cnblogs.com/yangfengwu/p/5295632.html)

- [ESP8266模块使用完整教程](http://blog.csdn.net/sherry_qin/article/details/50903540)   [（10.ESP8266完全教程资源包）](https://pan.baidu.com/s/1i4MmNTN)

### 烧入固件
下载官网固件刷写工具： http://bbs.espressif.com/download/file.php?id=385

- [ESP8266固件烧录详细过程](https://zhangtory.com/article/28/)
- [ESP8266刷机刷固件方法，ESP一键烧录工具使用教程](https://www.bigiot.net/talk/9.html)
- [ ESP8266（二）NODEMCU——烧录固件](http://blog.csdn.net/tianzhong123/article/details/50754872)
- [**如何刷入ESPUSH**](http://docs.espush.cn/tutorial.html#id3)

### 调试

- [ESP8266 ESP-01 调试全过程 – 使用指导](http://blog.csdn.net/fuyizhonhong/article/details/51317931)

**Comment by leon80900** [comment]
# 透传
[数据透传的概念](http://blog.csdn.net/chenlycly/article/details/7391038)

> 一般是指我们上层的数据以buf的形式经过底层模块去传送，底层只保证将这段buf传出去，而不去关心buf中具体是什么样的数据，不用去解析buf中的具体内容。
> 具体一点，以两个QQ客户端聊天为例，QQ的UI层定义了表示聊天信息的结构体（结构体中包含文字内容、文字颜色、文字字体及文字大小等信息），当QQ客户端发送信息时将信息填充到结构体中，然后再将结构体“压到”buf中，交给底层去传送，底层不知道buf中存放的是什么内容，也不用关心是什么内容，只要将buf发送给对端QQ就可以了。当对端QQ收到buf后，将buf中的内容转化成结构体，然后UI层去解析这个结构体就能得到具体的聊天信息了，从而将聊天信息显示到界面去。这就是一个具体的底层数据透传的例子。

**Comment by leon80900** [comment]
# 调试任务
1. 能否烧写固件
2. 能否收到WiFi发出内容
3. 设置工作模式

# 调试情况
一直处于下载中状态
![image](https://user-images.githubusercontent.com/26379556/28560779-800b418a-714e-11e7-92f0-5b6f79f99fba.png)

> Took 12.05s to erase flash block
> TEST !!!!
> FAST BAUD: 115200
> fACTORY REBOOT MODE:  False
> Running Cesanta flasher (speed 115200)...
> params:  ?
> MEMORY START
> ELSE.... 26
> Invalid head of packet ('')
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "threading.pyo", line 801, in __bootstrap_inner
>   File "download_panel_info.pyo", line 785, in run
>   File "esptool_api.pyo", line 763, in flash_download_thread
>   File "esptool_api.pyo", line 1761, in __init__
>   File "esptool_api.pyo", line 1646, in read_packet
> Exception: Invalid head of packet ('')
## F411 V0.1
### 不可烧入固件
![image](https://user-images.githubusercontent.com/26379556/28562220-fc329646-7153-11e7-923a-e84481aa294c.png)
### 烧入成功
![image](https://user-images.githubusercontent.com/26379556/28569974-a12f429c-716e-11e7-8bed-adeda49b636b.png)
### 总结原因
1. 烧入固件的软件问题
  - 应使用 官网固件刷写工具： http://bbs.espressif.com/download/file.php?id=385
2. 因原理图误导的连线问题

**Comment by leon80900** [comment]
开启刷写工具，选择固件及固件偏移，如下图所示：

![image](https://user-images.githubusercontent.com/26379556/28560427-311c75d6-714d-11e7-801d-e9227cd6b122.png)

点击 start ，模块将进入刷写模式，屏幕提示等待上电同步中，此时请拔下一块电池，并重新装入，使之重新定位，让模块真正进入刷写模式，并开始刷写固件，如下图所示，正在刷写中，以及刷写完成后的界面：

等待上电同步


![image](https://user-images.githubusercontent.com/26379556/28560324-c38d1a48-714c-11e7-9270-aa2ffc1fb5a1.png)

正在刷写中

![image](https://user-images.githubusercontent.com/26379556/28560366-ec13525c-714c-11e7-8a95-58a03e6d643d.png)


完成


![image](https://user-images.githubusercontent.com/26379556/28560372-f32e355c-714c-11e7-8495-851d0cbbb58a.png)
